# -*- coding: utf-8 -*-
"""Chabrier_Chris_HW4_Part1_Foundation_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1en-6M9erncstaSfAIPFP-OoqHw08LbLD

# **Part #1:**
"""

# Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Import original Olist data file from HW2 with features for model training

olist_orders_features = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DATA 6545 Data Science and MLOps/Data Files/HW3/Olist_Orders_Model_Dataset.csv')
olist_orders_features = olist_orders_features.drop(columns=['Unnamed: 0'])
olist_orders_features.head()

# Original model from HW2:

# Train/Test Split:
from sklearn.model_selection import train_test_split

X = olist_orders_features.drop(columns=['is_positive_review'])
y = olist_orders_features['is_positive_review']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print(f'X_train shape: {X_train.shape}')
print(f'X_test shape: {X_test.shape}')
print(f'Train balance: {y_train.mean():.1%} positive')
print(f'Test balance: {y_test.mean():.1%} positive')

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression

numeric_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = X.select_dtypes(include=['category', 'object']).columns.tolist()

numeric_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

categorical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])

preprocessor = ColumnTransformer([
    ('num', numeric_pipeline, numeric_cols),
    ('cat', categorical_pipeline, categorical_cols)
])

from sklearn.ensemble import RandomForestClassifier

random_forest_balanced = Pipeline([('preprocessor', preprocessor), ('classifier', RandomForestClassifier(class_weight='balanced', random_state=42))])

random_forest_balanced.fit(X_train, y_train)

# Hyperparameter Tuning

from sklearn.model_selection import RandomizedSearchCV

parameter_grid = {
    'classifier__n_estimators': [50, 100, 200],
    'classifier__max_depth': [5, 20, 100],
    'classifier__min_samples_split': [2, 5, 10]
}

random_search = RandomizedSearchCV(random_forest_balanced, param_distributions=parameter_grid, n_iter=10, scoring='recall', cv=5, n_jobs=-1, random_state=42)

random_fit = random_search.fit(X_train, y_train)

# Tuned Model Evaluation

from sklearn.metrics import (
    accuracy_score, confusion_matrix, classification_report,
    roc_curve, roc_auc_score,
    precision_recall_curve, average_precision_score,
    f1_score, precision_score, recall_score,
    ConfusionMatrixDisplay, RocCurveDisplay, PrecisionRecallDisplay
)

random_forest_tuned = random_fit.best_estimator_

y_pred_tuned = random_forest_tuned.predict(X_test)
y_prob_tuned = random_forest_tuned.predict_proba(X_test)[:, 1]

accuracy_HW2 = accuracy_score(y_test, y_pred_tuned)
precision_HW2 = precision_score(y_test, y_pred_tuned)
recall_HW2 = recall_score(y_test, y_pred_tuned)
f1_score_HW2 = f1_score(y_test, y_pred_tuned)
roc_auc_score_HW2 = roc_auc_score(y_test, y_prob_tuned)

print(f'Accuracy: {accuracy_HW2:.1%}')
print(f'Precision: {precision_HW2:.1%}')
print(f'Recall: {recall_HW2:.1%}')
print(f'f1 score: {f1_score_HW2:.1%}')
print(f'ROC-AUC score: {roc_auc_score_HW2:.1%}')

# Import full Olist data file from HW2 with all columns

olist_orders_full = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DATA 6545 Data Science and MLOps/Data Files/HW4/Olist_Orders_Full.csv')
olist_orders_full = olist_orders_full.drop(columns=['Unnamed: 0', 'Unnamed: 0.1'])
olist_orders_full.head()

# Handling null values in 'review_comment_message' column

olist_orders_drop = olist_orders_full.dropna(subset=['review_comment_message'])

olist_orders_drop.shape

# Install HuggingFace Transformers Library
!pip install transformers

from transformers import pipeline

sentiment = pipeline("sentiment-analysis", model="nlptown/bert-base-multilingual-uncased-sentiment", device=0)

olist_orders_sample = olist_orders_full.sample(n=500, random_state=42)

olist_orders_sample.shape

import numpy as np

def sentiment_prediction(text):
    try:
        result = sentiment(text[:1000])[0]
        stars = int(result["label"].split()[0])
        return stars
    except:
        return np.nan

olist_orders_sample['predicted_stars'] = olist_orders_sample['review_comment_message'].apply(sentiment_prediction)

olist_orders_sample = olist_orders_sample.dropna(subset=['predicted_stars'])

olist_orders_sample['foundation_pred'] = olist_orders_sample['predicted_stars'].apply(lambda x: 1 if x >= 4 else 0)

olist_orders_sample['foundation_pred']

# Foundation model performance

from sklearn.metrics import confusion_matrix

total = len(olist_orders_sample)
positive = olist_orders_sample['is_positive_review'].sum()
negative = total - positive

print(f'% Positive: {(positive / total) * 100}')
print(f'% Negative: {(negative / total) * 100}')

y_test_f = olist_orders_sample['is_positive_review']
y_pred_f = olist_orders_sample['foundation_pred']

cm_f = confusion_matrix(y_test_f, y_pred_f)
print(f'Confusion Matrix: \n{cm_f}')

olist_orders_sample = olist_orders_sample.rename(columns={'product_category_name': 'product_category'})

# Model performance comparison

column_names = X_test.columns.tolist()
column_names

rf_model_preds = random_forest_tuned.predict(olist_orders_sample[column_names])

olist_orders_sample['rf_model_pred'] = rf_model_preds

def metrics(y_test, y_pred):
    return {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred)
    }

foundation_metrics = metrics(olist_orders_sample['is_positive_review'], olist_orders_sample['foundation_pred'])
rf_metrics = metrics(olist_orders_sample['is_positive_review'], olist_orders_sample['rf_model_pred'])

comparison_df = pd.DataFrame([rf_metrics, foundation_metrics], index=['Random Forest Model', 'Foundation Model'])

print(comparison_df)

"""Overall, the random forest model I created in HW2 performs better compared to the foundation model on the same data set. The random forest model has a higher accuracy and F1 score while outperforming the foundation model in recall, although the foundation model outperforms the random forest model in precision, but the trade-off between the two is greater with the foundation model. One of the advantages of having a foundation model is that it is easier to implement given that it is already programmed to interpret and predict data in a specific way. This makes it suitable for situations where you need a solution implemented quickly and don't have time to fully validate the results (given that the specific foundation model has good reputability). A foundation model may not allow for the same flexibility for modifying the prediction outcomes to your specific use-case, however, and given that this model has a low recall but high precision (which is the opposite of what is optimal for this specific business problem), it would be useful here to have greater flexibility to make adjustments to these metrics."""